name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make build-library
  
  test:
    name: Test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: make test-library

  build-example:
    name: Build Example app
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make build-example
